apiVersion: v1
kind: ServiceAccount
metadata:
  name: demo-app
  namespace: default
  annotations:
    vault.patoarvizu.dev/auto-configure: "true"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
  namespace: default
spec:
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
      annotations:
        vault.patoarvizu.dev/agent-auto-inject: sidecar
    spec:
      serviceAccountName: demo-app
      containers:
      - name: demo-app
        image: patoarvizu/demos:hashiconf-demo
        env:
        - name: SECRET_PATH
          value: secret/demo-app
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 5

---

apiVersion: v1
kind: Service
metadata:
  name: demo-app
  namespace: default
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 30080
  selector:
    app: demo-app
  type: NodePort